import { mkdir, stat, writeFile } from "node:fs/promises";
import { join } from "node:path";
import pc from "picocolors";

const FOLDERS = ["source-notes", "topics", "people", "projects", "concepts", "questions"];

const INDEX_MD = `# Wiki Index

This wiki is curated by \`llm-wiki-gen\`. Source files live read-only under the
configured allowlist; all synthesis lives here under git.

## Sections

- [[source-notes/Index]] — per-source extracted notes
- [[topics/Index]] — concept pages
- [[people/Index]] — people pages
- [[projects/Index]] — project pages
- [[concepts/Index]] — concept primitives
- [[questions/Index]] — open questions

## Recent activity

\`\`\`dataview
TABLE file.mtime AS Updated
FROM ""
SORT file.mtime DESC
LIMIT 10
\`\`\`
`;

const LOG_MD = `# Log

Append-only chronological record of ingest, query, and lint runs.
Entries are written by \`llm-wiki-gen\` — do not edit by hand unless you know what you are doing.
`;

const README_VAULT = `# llm-wiki vault

Generated by \`llm-wiki-gen init\`. Open this folder in Obsidian and ensure the
**Dataview** community plugin is enabled.

- \`index.md\` — root navigation
- \`log.md\` — append-only activity log
- \`source-notes/\` — one note per ingested source
- \`topics/\`, \`people/\`, \`projects/\`, \`concepts/\` — synthesis pages
- \`questions/\` — open / answered questions

To regenerate: re-run \`llm-wiki-gen sync\` then \`llm-wiki-gen ingest\`.
`;

const UNRESOLVED_ALLOWED = `# One target per line. Listed targets will not trigger
# "broken-link" lint failures even if they don't resolve to a real page yet.
# Useful for aspirational topic pages the agent hasn't written yet.
`;

export interface InitOptions {
  vaultPath: string;
  /** If true, do not error when the vault already exists; only fill in missing pieces. */
  force?: boolean;
}

export interface InitReport {
  vaultPath: string;
  created: string[];
  skipped: string[];
}

export async function runInit(opts: InitOptions): Promise<InitReport> {
  const { vaultPath } = opts;
  const created: string[] = [];
  const skipped: string[] = [];

  await ensureDir(vaultPath, created);
  for (const folder of FOLDERS) {
    await ensureDir(join(vaultPath, folder), created);
  }

  await ensureFile(join(vaultPath, "index.md"), INDEX_MD, created, skipped);
  await ensureFile(join(vaultPath, "log.md"), LOG_MD, created, skipped);
  await ensureFile(join(vaultPath, "README.md"), README_VAULT, created, skipped);
  await ensureFile(
    join(vaultPath, ".unresolved-allowed.txt"),
    UNRESOLVED_ALLOWED,
    created,
    skipped,
  );

  // Folder index pages so [[topics/Index]] etc. resolve out of the box.
  for (const folder of FOLDERS) {
    await ensureFile(
      join(vaultPath, folder, "Index.md"),
      `# ${folder}\n\nPages in this folder.\n\n\`\`\`dataview\nLIST FROM "${folder}"\n\`\`\`\n`,
      created,
      skipped,
    );
  }

  process.stdout.write(
    `${pc.green("vault scaffolded")} at ${vaultPath}: ${created.length} created, ${skipped.length} kept\n`,
  );
  return { vaultPath, created, skipped };
}

async function ensureDir(p: string, created: string[]): Promise<void> {
  try {
    await stat(p);
  } catch {
    await mkdir(p, { recursive: true });
    created.push(p);
  }
}

async function ensureFile(
  p: string,
  content: string,
  created: string[],
  skipped: string[],
): Promise<void> {
  try {
    await stat(p);
    skipped.push(p);
  } catch {
    await writeFile(p, content, "utf-8");
    created.push(p);
  }
}
